name: Tag
version: '${project.version}'
main: dev.jamieisgeek.tag.Tag
api-version: 1.18
authors: [ JamieIsGeek ]
description: A game to play tag with your friends!
commands:
  tag:
    description: Main command for Tag

permissions:
  tag.*:
    description: Grants every permission for tag!
    default: op
    children:
      tag.join:
        default: not op
        description: Join the current queue!

      tag.leave:
        default: not op
        description: Leaves the current queue!

      tag.start:
        default: op
        description: Force starts the game!

      tag.end:
        default: op
        description: Force ends the game!